CourseProject1
IPopushay-portfolio/CourseProject1 pull request #1
Opened 2024-12-09 20:51 UTC by IPopushay-portfolio

2024-12-10 10:07 UTC, painassasin requested changes

2024-12-10 10:07 UTC, painassasin commented on .env
> +API_KEY=6xVHX1YfwYtA1ZjWACCbKPfvzl6SiNaO
Ключ в открытом виде хранить не нужно - файл `.env` нужно скрыт из репозитория

2024-12-10 10:07 UTC, painassasin commented on .idea/CourseProject1.iml
Директорию `.idea` нужно удалить из отслеживания

```
git rm --cached .idea/ -r`
```

2024-12-10 10:07 UTC, painassasin commented on logs/utils.logs
> +2024-11-08 14:28:29,029 - utils - INFO : ��������� ������ �� ����� {'amount': 100, 'currency': 'RUB'}
Проблемы с кодировкой - не понятно что пишется в лог(

2024-12-10 10:07 UTC, painassasin commented on src/__pycache__/__init__.cpython-313.pyc
Директории `__pycache__` нужно удалять из репозитория (см коммент по `.idea`)

2024-12-10 10:07 UTC, painassasin commented on src/config.py
> +API_KEY = "6xVHX1YfwYtA1ZjWACCbKPfvzl6SiNaO"
Ключ не нужно хранить в открытом виде - используй переменные окружения

2024-12-10 10:07 UTC, painassasin commented on src/external_api.py
> +    url = f"https://api.apilayer.com/exchangerates_data/convert?to={to_cur}&from={from_cur}&amount={amount})"
Параметры в `requests.get` нужно передавать через `params`, например:
```python
url = 'https://google.com'
params = {'q': 'python developer', `sourceid`: `chrome`}
response = requests.get(url, params=params)

2024-12-10 10:07 UTC, painassasin commented on src/external_api.py
> +    result = response.json()
Перед получением json-ответа нужно проверять статус-код и если он не 200 - сообщать об ошибке

2024-12-10 10:07 UTC, painassasin commented on src/main.py
Файл `main.py` должен быть в корне проекта, а не в модуле `src`

2024-12-10 10:07 UTC, painassasin commented on src/main.py
> +from black import datetime
Не правильный импорт
```python
from datetime import datetime`
```

2024-12-10 10:07 UTC, painassasin commented on src/utils.py
> +    data = get_transactions("C:\\Users\\user\\Desktop\\Python\\my_prj\\test_poetry\\data\\operations.json")
Путь до файла в таком виде не будет работать у любого другого разработчика на компьютере. Нужно исправить так, чтобы оно находило нужный файл в не зависимости от места запуска

2024-12-10 10:07 UTC, painassasin commented on tests/test_utils.py
> +from black import datetime
Не от туда импорт

2024-12-22 10:34 UTC, IPopushay-portfolio commented on src/main.py
> +from black import datetime
from datetime import timedelta

2024-12-22 10:34 UTC, IPopushay-portfolio commented on src/main.py
перенесла

2024-12-22 11:50 UTC, IPopushay-portfolio commented on .env
> +API_KEY=6xVHX1YfwYtA1ZjWACCbKPfvzl6SiNaO
git rm --cached  .env

2025-01-02 18:21 UTC, IPopushay-portfolio commented on tests/test_utils.py
> +from black import datetime
from datetime import datetime

2025-01-02 20:39 UTC, merged